// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhfG5yOMd7BT69uIsxol6ibKDwBHRyMc',
    appId: '1:595137705772:web:233f193b8ae75efdac5e89',
    messagingSenderId: '595137705772',
    projectId: 'proyectofinal-61d72',
    authDomain: 'proyectofinal-61d72.firebaseapp.com',
    storageBucket: 'proyectofinal-61d72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmCAAcFPD02paN8Q52sF4lQ2uN5MT6h0',
    appId: '1:595137705772:android:47e8ee312037d3deac5e89',
    messagingSenderId: '595137705772',
    projectId: 'proyectofinal-61d72',
    storageBucket: 'proyectofinal-61d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdH_GHDtqx8eVdI-KTf6bT2X533182NH4',
    appId: '1:595137705772:ios:67603098c877a5e3ac5e89',
    messagingSenderId: '595137705772',
    projectId: 'proyectofinal-61d72',
    storageBucket: 'proyectofinal-61d72.appspot.com',
    iosBundleId: 'com.example.aplicacionfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdH_GHDtqx8eVdI-KTf6bT2X533182NH4',
    appId: '1:595137705772:ios:b96cc88c16988f58ac5e89',
    messagingSenderId: '595137705772',
    projectId: 'proyectofinal-61d72',
    storageBucket: 'proyectofinal-61d72.appspot.com',
    iosBundleId: 'com.example.aplicacionfinal.RunnerTests',
  );
}
